GET HTTP://localhost:8081/api/Endereco

###

GET HTTP://localhost:8081/api/Endereco/3

###

POST HTTP://localhost:8081/api/Endereco
Content-Type: application/json

{
    "cep":00.000-000,
    "bairro":"exemplo",
    "numero": 20,
    "cidade":"Resende",
    "estado":"Rio de Janeiro",
    "rua":"rua exemplar",
    "complemento":"Ao lado do mercado"
    

}

###

PUT HTTP://localhost:8081/api/tiposCafe
Content-Type: application/json

{
    "cep":11.000-111,
    "bairro":"unifaa",
    "numero": 587,
    "cidade":"Resende",
    "estado":"Rio de Janeiro",
    "rua":"rua unifaa",
    "complemento":"Esquina do colegio municipal"

}

###

DELETE  HTTP://localhost:8081/api/Endereco/1
